# Generated by Django 5.2.6 on 2025-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("path", models.CharField(max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="ip_tracking_ip_addr_d89fd9_idx",
                    ),
                    models.Index(fields=["path"], name="ip_tracking_path_65894f_idx"),
                ],
            },
        ),
    ]
