# Generated by Django 5.2.6 on 2025-09-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0002_blockedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["country"], name="ip_tracking_country_d37b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["city"], name="ip_tracking_city_bcb1b9_idx"),
        ),
    ]
